---
language: python
python: "2.7"
sudo: required
services:
  - docker

install:
  - pip install -r molecule/requirements.txt

script:
  - travis_wait molecule test --all

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
